#!/usr/bin/env python3
"""
scout_form.py

Visit a new directory's submit page, snapshot the accessibility tree, dump
the detected fields, and write an adapter stub to adapters/<slug>.js.

This is the "I found a directory not in our target list" flow.

Usage:
  python scripts/scout_form.py \
    --url https://newdirectory.example/submit \
    --name "NewDirectory" \
    --profile product-profile.yaml
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ADAPTERS_DIR = REPO_ROOT / "adapters"
GENERIC = ADAPTERS_DIR / "generic.js"


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


STUB_TEMPLATE = """// adapters/{slug}.js — generated by scripts/scout_form.py
//
// Stub adapter for {name} ({url}).
// Scout detected these fields:
//   {fields}
//
// Customize the implementation below — by default it falls back to the
// generic adapter. Once you have site-specific logic (login, captcha,
// multi-step form), replace the import with a full implementation.

import {{ runGeneric }} from "./generic.js";

export async function run(opts) {{
  return runGeneric({{
    ...opts,
    target: opts.target || "{url}",
    siteName: "{name}",
  }});
}}

if (process.argv[1] && process.argv[1].endsWith("{slug}.js")) {{
  const opts = {{ profile: null, target: "{url}", siteName: "{name}", dryRun: false }};
  for (let i = 2; i < process.argv.length; i++) {{
    const a = process.argv[i];
    if (a === "--dry-run") opts.dryRun = true;
    else if (a === "--profile") opts.profile = process.argv[++i];
    else if (a === "--target") opts.target = process.argv[++i];
    else if (a === "--site-name") opts.siteName = process.argv[++i];
    else if (a === "--backend") opts.backend = process.argv[++i];
  }}
  run(opts).catch((e) => {{
    console.error(e);
    process.exit(1);
  }});
}}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--profile", required=True)
    ap.add_argument("--backend", default=None)
    args = ap.parse_args()

    # Run generic in dry-run mode to harvest the field map
    cmd = [
        "node", str(GENERIC),
        "--profile", args.profile,
        "--target", args.url,
        "--site-name", args.name,
        "--dry-run",
    ]
    if args.backend:
        cmd += ["--backend", args.backend]
    print(f"[scout] probing {args.url}")
    proc = subprocess.run(cmd, cwd=str(REPO_ROOT), capture_output=True, text=True)
    out = proc.stdout
    fields = "unknown"
    if "---REPORT-JSON---" in out:
        chunk = out.split("---REPORT-JSON---", 1)[1].split("---END-REPORT-JSON---", 1)[0]
        try:
            report = json.loads(chunk.strip())
            fields = ", ".join(
                f"{k}={v}" for k, v in (report.get("detected_fields") or {}).items() if v
            ) or "(none detected — site may need custom logic)"
            print("[scout] detected fields:", fields)
        except json.JSONDecodeError:
            pass
    else:
        print("[scout] no structured report — see raw output below:")
        print(out[-2000:])

    slug = slugify(args.name)
    target_path = ADAPTERS_DIR / f"{slug}.js"
    if target_path.exists():
        print(f"[scout] adapter already exists: {target_path}")
        return
    target_path.write_text(
        STUB_TEMPLATE.format(slug=slug, name=args.name, url=args.url, fields=fields),
        encoding="utf-8",
    )
    print(f"[scout] wrote stub adapter: {target_path}")


if __name__ == "__main__":
    main()
